services:
  todo_api_pg:
    container_name: todo_api_pg
    image: postgres:17.6
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-Abcd@1234}
      POSTGRES_DB: ${PG_DB:-todo_api_db}
    ports:
      - '5432:5432'
    networks:
      - todo_api_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  todo_api_pgadmin:
    container_name: todo_api_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-Abcd@1234}
    ports:
      - '5050:80'
    depends_on:
      todo_api_pg:
        condition: service_healthy
    networks:
      - todo_api_network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pg_data:

networks:
  todo_api_network:
    driver: bridge
